name: FoodSafety
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_localization: ^0.2.2

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

  provider: ^6.1.5+1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/food-safety.png"
  remove_alpha_ios: true
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/food-safety.png"
