// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart'
// //     show
// //         FirebaseOptions;
// // import 'package:flutter/foundation.dart'
// //     show
// //         defaultTargetPlatform,
// //         kIsWeb,
// //         TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey:
//         'AIzaSyCP7PRRnRgg4p4iryWlR_FTvQjVWl_QpKQ',
//     appId:
//         '1:877569395406:android:620a6a0d2f546612319e9f',
//     messagingSenderId:
//         '877569395406',
//     projectId:
//         'foodcheck-8023b',
//     storageBucket:
//         'foodcheck-8023b.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey:
//         'AIzaSyAuI40a__KCm-jWX-0DddPtxXPaRCc9jLQ',
//     appId:
//         '1:877569395406:ios:1239604e67ee9928319e9f',
//     messagingSenderId:
//         '877569395406',
//     projectId:
//         'foodcheck-8023b',
//     storageBucket:
//         'foodcheck-8023b.firebasestorage.app',
//     iosClientId:
//         '877569395406-rv77nev82d48tobusvkl8gb2fs79iv7o.apps.googleusercontent.com',
//     iosBundleId:
//         'com.example.newProject',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey:
//         'AIzaSyAMQAN0AlHG_bGFQZpI23M_NngRzr60LxQ',
//     appId:
//         '1:877569395406:web:33bbbd9df5f730fa319e9f',
//     messagingSenderId:
//         '877569395406',
//     projectId:
//         'foodcheck-8023b',
//     authDomain:
//         'foodcheck-8023b.firebaseapp.com',
//     storageBucket:
//         'foodcheck-8023b.firebasestorage.app',
//     measurementId:
//         'G-K1NPW9PMCN',
//   );
// }
